name: Examples
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Without issues
        uses: lagren/gosec-action@v1
        with:
          version: 2.6.1
          working-directory: example/good
      - name: With issues
        uses: lagren/gosec-action@v1
        with:
          version: 2.6.1
          working-directory: example/bad
        continue-on-error: true
