name: Tests
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn
      - run: yarn run test
